AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Retrieves an organization's package manifests from GitHub
Parameters:
  MongoUri:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/api/db/mongo_uri'
  GitHubAppPEM:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/api/github/app_pem'
  GitHubAppID:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/api/github/app_id'
Resources:
  OrgGitHubRetrieverDeadLetterQueue:
    Type: AWS::SQS::Queue
  OrgGitHubRetrieverQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: org-github-retriever-input
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt OrgGitHubRetrieverDeadLetterQueue.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 960
  OrgGitHubRetrieverFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 2048
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Events:
        OrgGitHubRetrieverEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OrgGitHubRetrieverQueue.Arn
            BatchSize: 1
      Policies:
        - AmazonSQSFullAccess
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - Statement:
          - Effect: Allow
            Action:
              - 'kms:Decrypt'
              - 'kms:ListKeys'
            Resource: '*'
      Environment:
        Variables:
          MONGO_URI: !Ref MongoUri
          GITHUB_APP_PEM: !Ref GitHubAppPEM
          GITHUB_APP_ID: !Ref GitHubAppID
